[build]
  command = "npm run build"
  publish = "out"

[dev]
  command = "npm run dev"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
